schema_version: 1

context:
  version: 1.20


package:
  name: libdeflate
  version: ${{ version }}

source:
  url: https://github.com/ebiggers/libdeflate/archive/v${{ version }}.tar.gz
  sha256: ed1454166ced78913ff3809870a4005b7170a6fd30767dc478a09b96847b9c2a

build:
  number: 0

requirements:
  build:
    - ${{ compiler('c') }}
    - if: unix
      then: make
    - cmake
    - if: win
      then: ninja
  run_exports:
    - ${{ pin_subpackage('libdeflate', upper_bound='x.x') }}

tests:
  - script:
      - if: unix
        then: test ! -f ${PREFIX}/lib/libdeflate.a
      - if: unix
        then: test -f ${PREFIX}/lib/libdeflate${SHLIB_EXT}
      - if: unix
        then: test -f ${PREFIX}/include/libdeflate.h
      - libdeflate-gzip -h
      - libdeflate-gunzip -h
      - if: win
        then: if not exist %LIBRARY_BIN%\\deflate.dll exit 1
      - if: win
        then: if not exist %LIBRARY_LIB%\\deflate.lib exit 1
      - if: win
        then: if not exist %LIBRARY_INC%\\libdeflate.h exit 1

about:
  license: MIT
  license_file: COPYING
  summary: libdeflate is a library for fast, whole-buffer DEFLATE-based compression and decompression.
  homepage: https://github.com/ebiggers/libdeflate

extra:
  recipe-maintainers:
    - dpryan79
    - rhpvorderman
    - hmaarrfk
