# Full credit goes to https://github.com/conda/conda-recipes for providing this recipe.
# It has been subsequently adapted for automated building with conda-forge.

context:
  version: 3.8.4

recipe:
  name: matplotlib-suite
  version: ${{ version }}

source:
  url: https://github.com/matplotlib/matplotlib/archive/v${{ version }}.tar.gz
  sha256: 7c4f370b7550eec8342c102f9dd80da3bec2895d7f514f5f6378764db4cb0e35

build:
  number: 2

outputs:
  - package:
      name: matplotlib-base
    build:
      # skip:
      #   - py<39
      script:
        - if: win
          then: build_base.bat
        - if: not win
          then: build_base.sh
        # - zlib
    requirements:
      build:
        - if: not win
          then: pkg-config
        - ${{ compiler('c') }}
        # - ${{ stdlib("c") }}
        - ${{ compiler('cxx') }}
        - if: unix
          then: libtool
        - pip
        - python >= 3.9
        - pybind11
        - numpy
        - certifi>=2020.06.20
      host:
        - python >= 3.9
        - pip
        - certifi>=2020.06.20
        - pybind11 >=2.6
        - freetype
        # freetype.pc requires zlib.pc
        - zlib
        - numpy
        - setuptools >=64
        - setuptools_scm >=7
        - setuptools_scm_git_archive
        - if: linux
          then: tk
      run:
        - python >= 3.9
        - certifi >=2020.06.20
        - contourpy >=1.0.1
        - cycler >=0.10
        - fonttools >=4.22.0
        - kiwisolver >=1.3.1
        - numpy >=1.21
        - packaging >=20.0
        - pillow >=8
        - pyparsing >=2.3.1
        - python-dateutil >=2.7
        - freetype
        - if: linux
          then: tk
        - if: match(py, '<3.10')
          then: importlib-resources>=3.2.0
    # tests:
    #   - python:
    #       imports:
    #         - matplotlib
    #         - matplotlib.pyplot
    #         - matplotlib._image
    #         - matplotlib._path
    #         - matplotlib._qhull
    #         - matplotlib._tri
    #         - matplotlib._ttconv
    #         - matplotlib.backends._backend_agg
    #         - matplotlib.ft2font
    #         - if: not win
    #           then: matplotlib.backends._tkagg
    #         - mpl_toolkits
    #         - pylab
    #       pip_check: false
    # script: build_base.bat  # [win]
    # script: build_base.sh  # [not win]
  - package:
      name: matplotlib
    # build:
      # skip:
      #   - py<39
    build: 
      script: 
        - python -m pip install .
    requirements:
      build: 
        - pip
        - python >= 3.9
        - pybind11
        - numpy
        - certifi>=2020.06.20
      host:
        - python >= 3.9
      run:
        - python >= 3.9
        - if: not osx and not aarch64 and not ppc64le and python_impl == "cpython"
          then: pyqt >=5.10
        # - pyqt >=5.10  # [not osx and not aarch64 and not ppc64le and python_impl == "cpython"]
        - tornado >=5
        - ${{ pin_subpackage('matplotlib-base', upper_bound="x.x.x") }}
    # tests:
    #   - python:
    #       imports:
    #         - matplotlib
    #       pip_check: false

about:
  license: PSF-2.0
  license_url: http://matplotlib.sourceforge.net/users/license.html
  license_file: LICENSE/LICENSE
  summary: Publication quality figures in Python
  description: |
    matplotlib is a python 2D plotting library which produces publication
    quality figures in a variety of hardcopy formats and interactive
    environments across platforms. matplotlib can be used in Python scripts,
    the Python and IPython shell (ala MATLAB or Mathematica), web
    application servers, and six graphical user interface toolkits.
  homepage: http://matplotlib.org/
  repository: https://github.com/matplotlib/matplotlib/
  documentation: http://matplotlib.org/contents.html

extra:
  recipe-maintainers:
    - mdboom
    - ocefpaf
    - pelson
    - tacaswell
    - dopplershift
