repos:
  -   repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.5.0
      hooks:
        -   id: check-yaml
            exclude: ^(recipes/)
        -   id: end-of-file-fixer
            exclude: ^(recipes/|docs/)
        -   id: trailing-whitespace
            exclude: ^(recipes/|docs/)
        -   id: debug-statements
  # Use ruff for python examples
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.3.4
    hooks:
      - id: ruff
        args: [ --fix, --exit-non-zero-on-fix ]
        exclude: ^recipes
  - repo: https://github.com/rhysd/actionlint
    rev: v1.7.1
    hooks:
      - id: actionlint
  - repo: https://github.com/codespell-project/codespell
    rev: v2.2.6
    hooks:
    - id: codespell
      exclude: ^(recipes/|docs/)
