local:
- path: recipes/boltons/recipe.yaml
- path: recipes/pthread-stubs/recipe.yaml
rattler-build:
  branch: main
  url: https://github.com/prefix-dev/rattler-build.git
repositories:
- branch: main
  recipes:
  - path: examples/rich/recipe.yaml
  - path: examples/curl/recipe.yaml
  url: https://github.com/prefix-dev/rattler-build.git
