[project]
name = "reproducible-builds-rattler-build"
version = "0.1.0"
description = "Add a short description here"
authors = ["nichmor <nmorkotilo@gmail.com>"]
channels = ["conda-forge"]
platforms = ["osx-arm64", "linux-64", "osx-64", "win-64"]

[tasks]
# Rewrite the readme with the updated data
rewrite-readme = "repror rewrite-readme"
# Used to generate build matrix for github
generate-recipes = "repror generate-recipes"
# Build recipes in the recipes folder
build-recipe = "repror build-recipe"
# Same as above but skip rattler-build setup
build-recipe-skip = "repror --skip-setup-rattler-build build-recipe"
# Rebuild a single recipe using the python script
rebuild-recipe = "repror rebuild-recipe"
# Convert a meta.yaml to a recipe.yaml
convert-recipe = "convert-conda-recipe"
# Run tests
test = "pytest tests/"


# Formatting python
[feature.dev.dependencies]
ruff = ">=0.4.7,<0.5"
[feature.dev.tasks]
# Format recipes using ruff
fmt = "ruff format"


# Default dependencies
[dependencies]
python = "~=3.12"
rattler-build = "*"
pyyaml = "*"
pytest = "*"
typer = ">=0.12.3,<0.13"
jinja2 = "*"
python-dotenv = "*"
pandas = "*"
sqlmodel = "*"
pydantic = "*"

[pypi-dependencies]
repror = { path = ".", editable = true }
conda-recipe-manager = { git = "https://github.com/conda-incubator/conda-recipe-manager.git" }


[environments]
dev = {features = ["dev"], no-default-feature = true}
