[project]
name = "reproducible-builds-rattler-build"
version = "0.1.0"
description = "Add a short description here"
authors = ["nichmor <nmorkotilo@gmail.com>"]
channels = ["conda-forge"]
platforms = ["osx-arm64", "linux-64", "osx-64", "win-64"]

[tasks]
# Rewrite the readme with the updated data
rewrite-readme = "repor rewrite-readme"
# Used to generate build matrix for github
generate-recipes = "repror generate-recipes"
# Build recipes using rattler-build for the current platform
# TODO: make something different for this command
build-all-recipes = "rattler-build build --recipe-dir recipes --output-dir recipes/outputs"
# Build a single recipe using the python script
build-recipe = "repror build-recipe"
# Rebuild a single recipe using the python script
rebuild-recipe = "repror rebuild-recipe"

convert-recipe = "convert-conda-recipe"


# Formatting python
[feature.dev.dependencies]
ruff = ">=0.4.7,<0.5"
[feature.dev.tasks]
# Format recipes using ruff
fmt = "ruff format"


# Default dependencies
[dependencies]
python = "~=3.12"
matplotlib = "*"
rattler-build = "*"
pyyaml = "*"
pytest = "*"
typer = ">=0.12.3,<0.13"

[pypi-dependencies]
repror = { path = ".", editable = true }
conda-recipe-manager = { git = "https://github.com/conda-incubator/conda-recipe-manager.git" }


[environments]
dev = {features = ["dev"], solve-group = "default"}
