[project]
name = "reproducible-builds-rattler-build"
version = "0.1.0"
description = "Add a short description here"
authors = ["nichmor <nmorkotilo@gmail.com>"]
channels = ["conda-forge"]
platforms = ["osx-arm64", "linux-64", "osx-64", "win-64"]

[tasks]
build_recipes = "python src/repror/generate_chart_data.py"
plot_data = "python src/repror/plot.py"

[dependencies]
python = "~=3.10"
matplotlib = "*"
rattler-build = "*"
pyyaml = "*"
pytest = "*"

[pypi-dependencies]
repror = {path = ".", editable = true}
conda-recipe-manager = { git = "https://github.com/conda-incubator/conda-recipe-manager.git" }
