schema_version: 1

context:
  name: aom
  version: 3.9.1

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://storage.googleapis.com/aom-releases/libaom-${{ version }}.tar.gz
  sha256: dba99fc1c28aaade28dda59821166b2fa91c06162d1bc99fde0ddaad7cecc50e
  patches:
    - 0001-Fix-compilation-flags-for-win32.patch
    - 0002-Remove-all-reference-of-aom_static.patch

build:
  number: 0

requirements:
  build:
    - ${{ compiler('c') }}
    # - ${{ stdlib("c") }}
    - ${{ compiler('cxx') }}
    - cmake
    - perl
    - nasm
    - if: unix
      then: make
  run_exports:
    - ${{ pin_subpackage('aom', upper_bound='x.x') }}

tests:
  - script:
      - if: build_platform == target_platform
        then: aomenc --help
      - if: build_platform == target_platform
        then: aomdec --help
      - if: unix
        then: test -f ${PREFIX}/include/aom/aom.h
      - if: unix
        then: test -f ${PREFIX}/lib/libaom${SHLIB_EXT}
      - if: unix
        then: test ! -f ${PREFIX}/lib/libaom.a
      - if: unix
        then: test -f ${PREFIX}/lib/pkgconfig/aom.pc
      - if: win
        then: if not exist %LIBRARY_INC%\\aom\\aom.h exit 1
      - if: win
        then: if not exist %LIBRARY_BIN%\\aom.dll exit 1

about:
  license: BSD-2-Clause
  license_file: LICENSE
  summary: Alliance for Open Media video codec
  description: |
    AOMedia Video 1 (AV1), is an open, royalty-free video coding format designed for
    video transmissions over the Internet.
  homepage: https://aomedia.org/
  repository: https://aomedia.googlesource.com/aom/

extra:
  recipe-maintainers:
    - matthiasdiener
