schema_version: 1

context:
  version: 70.0.0

package:
  name: setuptools
  version: ${{ version }}

source:
  url: https://pypi.io/packages/source/s/setuptools/setuptools-${{ version }}.tar.gz
  sha256: f211a66637b8fa059bb28183da127d4e86396c991a942b028c6650d4319c3fd0
  patches:
    # distutils patches from python-feedstock
    - patches/0021-Add-d1trimfile-SRC_DIR-to-make-pdbs-more-relocatable.patch

build:
  number: 0
  noarch: python

requirements:
  host:
    - python >=3.8
  run:
    - python >=3.8

tests:
  - python:
      imports:
        - setuptools
        - pkg_resources

about:
  license: MIT
  license_file: LICENSE
  summary: Download, build, install, upgrade, and uninstall Python packages
  description: |
    Setuptools is a fully-featured, actively-maintained, and stable library
    designed to facilitate packaging Python projects.
  homepage: https://github.com/pypa/setuptools
  repository: https://github.com/pypa/setuptools
  documentation: http://pythonhosted.org/setuptools/

extra:
  recipe-maintainers:
    - xhochy
    - rgommers
    - jakirkham
    - msarahan
    - ocefpaf
    - nicoddemus
    - isuruf
