schema_version: 1

context:
  name: libnsl
  version: 2.0.1

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://github.com/thkukuk/${{ name }}/archive/v${{ version }}.tar.gz
  sha256: 59048b53be8d3904bf939313debf13956a881b0de79da40f7719a77bcd1e9c53

build:
  number: 0
  skip:
    - not linux

requirements:
  build:
    - if: unix
      then: gnuconfig
    - ${{ compiler('c') }}
    - make
    - pkg-config
    - libtool
  run_exports:
    - ${{ pin_subpackage('libnsl', max_pin='x.x') }}

tests:
  - script:
      - test -f ${PREFIX}/lib/libnsl.so

about:
  license: LGPL-2.1-only
  license_file: COPYING
  summary: Public client interface library for NIS(YP)
  homepage: https://github.com/thkukuk/libnsl

extra:
  recipe-maintainers:
    - izahn
    - isuruf
    - xhochy
