schema_version: 1

context:
  name: fonttools
  version: 4.53.0

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.io/packages/source/${{ name[0] }}/${{ name }}/fonttools-${{ version }}.tar.gz
  sha256: c93ed66d32de1559b6fc348838c7572d5c0ac1e4a258e76763a5caddd8944002

build:
  number: 0
  skip:
    - py2k
  script: python -m pip install . --no-deps -vv
  python:
    entry_points:
      - fonttools = fontTools.__main__:main
      - ttx = fontTools.ttx:main
      - pyftsubset = fontTools.subset:main
      - pyftmerge = fontTools.merge:main

requirements:
  build:
    - if: build_platform != target_platform
      then: python
    - if: build_platform != target_platform
      then: cross-python_${{ target_platform }}
    - if: build_platform != target_platform
      then: cython
    - ${{ compiler('c') }}
    # - ${{ stdlib("c") }}
  host:
    - cython
    - pip
    - python
  run:
    - python
    - brotli
    - munkres
    - if: py<311
      then: unicodedata2 >=14.0.0

tests:
  - python:
      imports:
        - fontTools
        - fontTools.ttLib
        - fontTools.cffLib
      pip_check: true
  - requirements:
      run:
        - pip
    script:
      - fonttools --help
      - fonttools subset --help
      - ttx -h
      - pyftsubset --help

about:
  license: MIT
  license_file: LICENSE
  summary: fontTools is a library for manipulating fonts, written in Python.
  description: |
    fontTools is a library for manipulating fonts, written in Python. The
    project includes the TTX tool, that can convert TrueType and OpenType
    fonts to and from an XML text format, which is also called TTX. It
    supports TrueType, OpenType, AFM and to an extent Type 1 and some
    Mac-specific formats. The project has a BSD-style open-source licence.

  homepage: https://github.com/fonttools/fonttools
  repository: https://github.com/fonttools/fonttools
  documentation: https://groups.google.com/forum/#!forum/fonttools

extra:
  recipe-maintainers:
    - CJ-Wright
    - dopplershift
    - tacaswell
