{% set version = "6.3.0" %}

package:
  name: gmp
  version: {{ version }}

source:
  url:
    - https://gmplib.org/download/gmp/gmp-{{ version }}.tar.xz
    - https://ftp.gnu.org/gnu/gmp/gmp-{{ version }}.tar.xz
  sha256: a3c2b80201b89e68616f4ad30bc66aee4927c3ce50e33929ca819d5c43538898

build:
  number: 1
  skip: true  # [win]
  run_exports:
    - {{ pin_subpackage("gmp") }}

requirements:
  build:
    - gnuconfig  # [unix]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - m4
    - make
  host:

test:
  requires:
    - {{ compiler('c') }}

  files:
    - test.c

  commands:
    - test -f ${PREFIX}/lib/libgmp.a        # [unix]
    - test -f ${PREFIX}/lib/libgmp.dylib    # [osx]
    - test -f ${PREFIX}/lib/libgmp.so       # [linux]
    - test -f ${PREFIX}/lib/libgmpxx.a      # [unix]
    - test -f ${PREFIX}/lib/libgmpxx.dylib  # [osx]
    - test -f ${PREFIX}/lib/libgmpxx.so     # [linux]

about:
  home: http://gmplib.org/
  license: GPL-2.0-or-later OR LGPL-3.0-or-later
  license_file: COPYING.LESSERv3
  summary: The GNU multiprecision library.

extra:
  recipe-maintainers:
    - asmeurer
    - isuruf
    - jakirkham
