schema_version: 1

context:
  version: 2024.2.2

package:
  name: ca-certificates
  version: ${{ version }}

source:
  url: https://pypi.io/packages/source/c/certifi/certifi-${{ version }}.tar.gz
  sha256: 0569859f95fc761b18b45ef421b1290a0f65f147e92a1e5eb3e635f9a5e4e66f

build:
  number: 0

tests:
  - requirements:
      run:
        - curl
    script:
      - if: unix
        then: "test -f \"${PREFIX}/ssl/cacert.pem\""
      - if: unix
        then: "test -f \"${PREFIX}/ssl/cert.pem\""
      - if: win
        then: if not exist %LIBRARY_PREFIX%\\ssl\\cacert.pem exit 1
      - if: win
        then: if not exist %LIBRARY_PREFIX%\\ssl\\cert.pem exit 1
      - if: unix
        then: "curl --cacert \"${PREFIX}/ssl/cacert.pem\" https://www.google.com"
      - if: win
        then: curl --cacert %LIBRARY_PREFIX%\\ssl\\cacert.pem https://www.google.com

about:
  license: ISC
  license_file: LICENSE
  summary: Certificates for use with other packages.
  homepage: https://github.com/conda-forge/ca-certificates-feedstock

extra:
  recipe-maintainers:
    - jakirkham
    - msarahan
    - mwcraig
    - ocefpaf
    - patricksnape
    - pelson
    - scopatz
