context:
  version: 5.9.8

package:
  name: psutil
  version: ${{ version }}

source:
  url: https://pypi.io/packages/source/p/psutil/psutil-${{ version }}.tar.gz
  sha256: 6be126e3225486dff286a8fb9a06246a5253f4c7c53b475ea5f5ac934e64194c
  patches:
    - 0001-Add-missing-includes-for-macOS.patch

build:
  number: 0
  script:
    # macOS renamed this variable, but it is `NULL` in either case.
    # Workaround the missing definition by setting it to `0`.
    #
    # xref: https://github.com/giampaolo/psutil/issues/2354
    # - if: osx
    #   then: "export CFLAGS=\"${CFLAGS} -DkIOMainPortDefault=0\""
    - python -m pip install --ignore-installed --no-deps .

requirements:
  build:
    - if: build_platform != target_platform
      then: python
    - if: build_platform != target_platform
      then: cross-python_${{ target_platform }}
    - ${{ compiler('c') }}
  host:
    - python
    - pip
    - setuptools >=43
    - wheel
  run:
    - python

tests:
  - python:
      imports:
        - psutil
        - if: unix
          then: psutil._psutil_posix
        - if: linux
          then: psutil._psutil_linux
        - if: osx
          then: psutil._psutil_osx
        - if: win
          then: psutil._psutil_windows
        - psutil.tests
      pip_check: false

about:
  license: BSD-3-Clause
  license_file: LICENSE
  summary: A cross-platform process and system utilities module for Python
  description: |
    psutil (process and system utilities) is a cross-platform library for
    retrieving information on running processes and system utilization (CPU,
    memory, disks, network) in Python. It is useful mainly for system
    monitoring, profiling and limiting process resources and management of
    running processes.
  homepage: https://github.com/giampaolo/psutil
  repository: https://github.com/giampaolo/psutil
  documentation: http://pythonhosted.org/psutil/

extra:
  recipe-maintainers:
    - gqmelo
    - jakirkham
    - pelson
    - nehaljwani
