schema_version: 1

context:
  version: 2.038

package:
  name: font-ttf-source-code-pro
  version: ${{ version }}

source:
  url: https://github.com/adobe-fonts/source-code-pro/archive/refs/tags/${{ version }}R-ro/1.058R-it/1.018R-VAR.tar.gz
  sha256: d8f879fefd66ecb7291ea2d73984b9c0a97fb499424e58290ba6b81787d0c725

build:
  number: 0
  noarch: generic

tests:
  - requirements:
      run:
        - bzip2
    script:
      - if: unix
        then: test -f ${PREFIX}/fonts/SourceCodePro-Black.ttf
      - if: unix
        then: test -f ${PREFIX}/fonts/SourceCodePro-BlackIt.ttf
      - if: unix
        then: test -f ${PREFIX}/fonts/SourceCodePro-Bold.ttf
      - if: unix
        then: test -f ${PREFIX}/fonts/SourceCodePro-BoldIt.ttf
      - if: unix
        then: test -f ${PREFIX}/fonts/SourceCodePro-ExtraLight.ttf
      - if: unix
        then: test -f ${PREFIX}/fonts/SourceCodePro-ExtraLightIt.ttf
      - if: unix
        then: test -f ${PREFIX}/fonts/SourceCodePro-It.ttf
      - if: unix
        then: test -f ${PREFIX}/fonts/SourceCodePro-Light.ttf
      - if: unix
        then: test -f ${PREFIX}/fonts/SourceCodePro-LightIt.ttf
      - if: unix
        then: test -f ${PREFIX}/fonts/SourceCodePro-Medium.ttf
      - if: unix
        then: test -f ${PREFIX}/fonts/SourceCodePro-MediumIt.ttf
      - if: unix
        then: test -f ${PREFIX}/fonts/SourceCodePro-Regular.ttf
      - if: unix
        then: test -f ${PREFIX}/fonts/SourceCodePro-Semibold.ttf
      - if: unix
        then: test -f ${PREFIX}/fonts/SourceCodePro-SemiboldIt.ttf

about:
  summary: A set of fonts that have been designed to work well in UI environments
  license: OFL-1.1
  license_file: LICENSE.md
  homepage: https://adobe-fonts.github.io/source-code-pro/

extra:
  recipe-maintainers:
    - dbast
