schema_version: 1

context:
  version: 24.0

package:
  name: pip
  version: ${{ version }}

source:
  url: https://pypi.io/packages/source/p/pip/pip-${{ version }}.tar.gz
  sha256: ea9bd1a847e8c5774a5777bb398c19e80bcd4e2aa16a4b301b718fe6f593aba2

build:
  number: 0
  noarch: python
  python:
    entry_points:
      - pip = pip._internal.cli.main:main
      - pip3 = pip._internal.cli.main:main

requirements:
  host:
    - python >=3.7
    - setuptools
  run:
    - python >=3.7
    - setuptools
    - wheel

tests:
  - python:
      imports:
        - pip
  - script:
      - pip -h
      - pip list

about:
  license: MIT
  license_file: LICENSE.txt
  summary: PyPA recommended tool for installing Python packages
  homepage: https://pip.pypa.io/en/stable/
  repository: https://github.com/pypa/pip
  documentation: https://pip.pypa.io/en/stable/

extra:
  recipe-maintainers:
    - jakirkham
    - msarahan
    - pelson
    - ocefpaf
    - mingwandroid
