schema_version: 1

context:
  version: 1.3.1

package:
  name: libopus
  version: ${{ version }}

source:
  url: https://github.com/xiph/opus/archive/v${{ version }}.tar.gz
  sha256: 4834a8944c33a7ecab5cad9454eeabe4680ca1842cb8f5a2437572dbf636de8f
  patches:
    - cmake_use_packageversion.patch

build:
  number: 1

requirements:
  build:
    - ${{ compiler('c') }}
    - if: unix
      then: make
    - if: unix
      then: autoconf
    - if: unix
      then: libtool
    - if: unix
      then: automake
    - if: win
      then: ninja
    - if: win
      then: cmake
  run_exports:
    - ${{ pin_subpackage('libopus', upper_bound='x') }}

tests:
  - script:
      - if: unix
        then: test -f ${PREFIX}/lib/libopus${SHLIB_EXT}
      - if: win
        then: if exist %LIBRARY_LIB%\opus.lib (exit 0) else (exit 1)
      - if: win
        then: if exist %LIBRARY_BIN%\opus.dll (exit 0) else (exit 1)

about:
  license: BSD-3-Clause
  license_file: COPYING
  summary: Opus Interactive Audio Codec
  description: |
    Opus is a totally open, royalty-free, highly versatile
    audio codec. Opus is unmatched for interactive speech
    and music transmission over the Internet, but is also
    intended for storage and streaming applications. It is
    standardized by the Internet Engineering Task Force
    (IETF) as RFC 6716 which incorporated technology from
    Skype's SILK codec and Xiph.Org's CELT codec.
  homepage: http://opus-codec.org/
  repository: http://opus-codec.org/development/
  documentation: http://opus-codec.org/docs/

extra:
  recipe-maintainers:
    - wolfv
