schema_version: 1

context:
  version: 0.18.6

package:
  name: ruamel.yaml
  version: ${{ version }}

source:
  url: https://pypi.io/packages/source/r/ruamel.yaml/ruamel.yaml-${{ version }}.tar.gz
  sha256: 8b27e6a217e786c6fbe5634d8f3f11bc63e0f80f6a5890f28863d9c45aac311b

build:
  number: 0
  script: 
    - python -m pip install . --no-deps -vv

requirements:
  build:
    - if: build_platform != target_platform
      then: python
    - if: build_platform != target_platform
      then: cross-python_${{ target_platform }}
    - ${{ compiler('c') }}
  host:
    - python
    - pip
    - ruamel
  run:
    - python
    - ruamel.yaml.clib >=0.1.2

tests:
  - python:
      imports:
        - ruamel.yaml
      pip_check: false

about:
  license: MIT
  license_file: LICENSE
  summary: "A YAML package for Python. It is a derivative of Kirill Simonov's PyYAML 3.11 which supports YAML1.1"
  homepage: https://sourceforge.net/p/ruamel-yaml

extra:
  recipe-maintainers:
    - jakirkham
    - pelson
    - mwcraig
    - ocefpaf
    - mbargull
    - xhochy
    - davidbrochart
