schema_version: 1

context:
  name: toml
  version: 0.10.2
  sha256: b3bda1d108d5dd99f4a20d24d9c348e91c4db7ab1b749200bded2f839ccbe68f

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.io/packages/source/${{ name[0] }}/${{ name }}/${{ name }}-${{ version }}.tar.gz
  sha256: ${{ sha256|lower }}
  file_name: ${{ name }}-${{ version }}.tar.gz

build:
  number: 0
  noarch: python
  script: python -m pip install . --no-deps -vv

requirements:
  build:
    - python >=2.7
    - pip
  run:
    - python >=2.7

# tests:
#   - python:
#       imports:
#         - toml
#   - script:
#       - if: not win
#         then: conda inspect linkages -p $PREFIX toml
#       - if: osx
#         then: conda inspect objects -p $PREFIX toml

about:
  license: MIT
  license_file: LICENSE
  summary: Python lib for TOML.
  homepage: https://github.com/uiri/toml

extra:
  recipe-maintainers:
    - rlaverde
    - holgern
