{% set name = "openh264" %}
{% set version = "2.4.1" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/cisco/openh264/archive/v{{ version }}.tar.gz
  sha256: 8ffbe944e74043d0d3fb53d4a2a14c94de71f58dbea6a06d0dc92369542958ea

build:
  number: 0
  run_exports:
    # new so names and compatibility changes on minor version
    # But then things changed in 2.3.1
    # https://abi-laboratory.pro/?view=timeline&l=openh264
    - {{ pin_subpackage('openh264', max_pin='x.x.x') }}

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ compiler('c') }}
    - pkg-config
    - nasm
    - make    # [unix]
    - meson   # [win]
    - ninja   # [win]

test:
  commands:
    - h264enc -h
    - h264dec | grep welsdec.cfg       # [unix]
    - h264dec | findstr welsdec.cfg    # [win]
    - test -f $PREFIX/lib/libopenh264${SHLIB_EXT}                         # [unix]
    - if not exist %PREFIX%\\Library\\bin\\openh264-7.dll exit 1          # [win]
    - if not exist %PREFIX%\\Library\\lib\\openh264.lib exit 1            # [win]
    - if not exist %PREFIX%\\Library\\lib\\pkgconfig\\openh264.pc exit 1  # [win]

about:
  home: http://www.openh264.org/
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE
  summary: OpenH264 is a codec library which supports H.264 encoding and decoding
  dev_url: https://github.com/cisco/openh264
  doc_url: https://github.com/cisco/openh264

extra:
  recipe-maintainers:
    - 183amir
    - sdvillal
    - hmaarrfk
