schema_version: 1

context:
  xorg_name: kbproto
  xorg_category: proto
  name: xorg-kbproto
  version: 1.0.7
  sha256: f882210b76376e3fa006b11dbd890e56ec0942bc56e65d1249ff4af86f90b857

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://www.x.org/releases/individual/${{ xorg_category }}/${{ xorg_name }}-${{ version }}.tar.bz2
  sha256: f882210b76376e3fa006b11dbd890e56ec0942bc56e65d1249ff4af86f90b857
  file_name: ${{ name }}-${{ version }}.tar.bz2

build:
  number: 1002
  # detect_binary_files_with_prefix: true

requirements:
  build:
    - if: win
      then: m2-autoconf
    - if: win
      then: m2-automake${{ am_version }}
    - if: win
      then: m2-libtool
    - if: win
      then: m2w64-pkg-config
    - if: not win
      then: pkg-config
    - if: win
      then: posix
    - if: unix
      then: gnuconfig
    - if: unix
      then: ${{ compiler('c') }}
    - if: win
      then: ${{ compiler('m2w64_c') }}
    - if: unix
      then: make
    - if: unix
      then: autoconf
    - if: unix
      then: automake
    - if: unix
      then: gettext
    - if: unix
      then: libtool
  host:
    - xorg-util-macros

# tests:
#   - commands

about:
  license: MIT
  license_file: COPYING
  summary: X.org keyboard-related C prototypes.
  homepage: https://www.x.org/

extra:
  recipe-maintainers:
    - pkgw
