schema_version: 1

context:
  version: 1.1.39

package:
  name: libxslt
  version: ${{ version }}

source:
  url: https://download.gnome.org/sources/libxslt/${{ version[0:3] }}/libxslt-${{ version }}.tar.xz
  sha256: 2a20ad621148339b0759c4d4e96719362dee64c9a096dbba625ba053846349f0
  patches:
    - 0001-Make-and-install-a-pkg-config-file-on-Windows.patch
    - 0002-win-profiler-config.patch

build:
  number: 0

requirements:
  build:
    - ${{ compiler('c') }}
    - if: unix
      then: gnuconfig
    - make
    - pkg-config
  host:
    - libxml2
  run_exports:
    - ${{ pin_subpackage('libxslt') }}

tests:
  - requirements:
      run:
        - pkg-config
    script:
      - xsltproc --version
      - pkg-config --cflags libxslt libexslt
      - pkg-config --libs libxslt libexslt

about:
  license: MIT
  license_file: COPYING
  summary: The XSLT C library developed for the GNOME project
  description: |
    "Libxslt is the XSLT C library developed for the GNOME project.
    XSLT itself is a an XML language to define transformation for XML.
    Libxslt is based on libxml2 the XML C library developed for the GNOME project.
    It also implements most of the EXSLT set of processor-portable extensions functions
    and some of Saxon's evaluate and expressions extensions."
  homepage: https://gitlab.gnome.org/GNOME/libxslt
  repository: https://gitlab.gnome.org/GNOME/libxslt
  documentation: https://gitlab.gnome.org/GNOME/libxslt/-/wikis

extra:
  recipe-maintainers:
    - mbargull
    - ocefpaf
    - scopatz
