schema_version: 1

context:
  name: _openmp_mutex
  version: 4.5
  build: 2

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  path: .

build:
  # Remove track_features because directly depending on mutex=*=*llvm
  # would make the downstream package have low priority
  # For eg: newer blas packages are not used by the solver
  # track_features:
  #  - llvm_openmp
  number: ${{ build }}
  string: ${{ build }}_kmp_llvm
  skip:
    - not linux
  always_include_files:
    # this major version has to match the libgomp version from gcc
    - lib/libgomp.so.1

requirements:
  host:
  run:
    - llvm-openmp >=9.0.1
    - if: linux64 or ppc64le
      then: _libgcc_mutex ${{ _libgcc_mutex }}
  run_exports:
    - ${{ pin_subpackage('_openmp_mutex', max_pin=None) }}
  ignore_run_exports:
    from_package:
      - _openmp_mutex

tests:
  - files:
      recipe:
        - omp_hello.c
    requirements:
      run:
        - ${{ compiler('c') }}
        - ${{ compiler('cxx') }}
    script:
      - test -f $PREFIX/lib/libgomp.so.1
      - if [ ! "$PREFIX/lib/libgomp.so.1" -ef "$PREFIX/lib/libomp.so" ]; then exit 1;:
          - fi
      - rm -f omp_hello && ${CC} -v -fopenmp omp_hello.c -o omp_hello && ./omp_hello
      - if: linux
        then: ldd omp_hello
      - rm -f omp_hello && ${CXX} -v -fopenmp omp_hello.c -o omp_hello && ./omp_hello
      - if: linux
        then: ldd omp_hello

about:
  summary: OpenMP Implementation Mutex
  license: BSD-3-Clause
  license_file: LICENSE
  homepage: https://github.com/conda-forge/openmp-feedstock

extra:
  recipe-maintainers:
    - isuruf
    - beckermr
