schema_version: 1

context:
  version: 1.16.0

package:
  name: wrapt
  version: ${{ version }}

source:
  url: https://pypi.io/packages/source/w/wrapt/wrapt-${{ version }}.tar.gz
  sha256: 5f370f952971e7d17c7d1ead40e49f32345a7f7a5373571ef44d800d06b1899d

build:
  number: 0
  skip:
    - py<37
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  build:
    - if: build_platform != target_platform
      then: python
    - if: build_platform != target_platform
      then: cross-python_${{ target_platform }}
    - ${{ compiler('c') }}
  host:
    - python
    - setuptools >=38.3.0
    - pip
  run:
    - python

tests:
  - python:
      imports:
        - wrapt
      pip_check: true
  - requirements:
      run:
        - pip
    script: commands

about:
  license: BSD-2-Clause
  license_file: LICENSE
  summary: Module for decorators, wrappers and monkey patching
  description: |
    The aim of the wrapt module is to provide a transparent object proxy for
    Python, which can be used as the basis for the construction of function
    wrappers and decorator functions.
  homepage: https://github.com/GrahamDumpleton/wrapt
  repository: https://github.com/GrahamDumpleton/wrapt
  documentation: http://wrapt.readthedocs.org/en/latest/

extra:
  recipe-maintainers:
    - jakirkham
    - nehaljwani
    - ocefpaf
