schema_version: 1

context:
  version: 0.12.1

package:
  name: cycler
  version: ${{ version }}

source:
  url: https://pypi.io/packages/source/c/cycler/cycler-${{ version }}.tar.gz
  sha256: 88bb128f02ba341da8ef447245a9e138fae777f6a23943da4540077d3601eb1c

build:
  number: 0
  noarch: python
  script:
    - python -m pip install . -vv

requirements:
  host:
    - python >=3.8
    - setuptools >=61
    - pip
  run:
    - python >=3.8

tests:
  - python:
      imports:
        - cycler
  - requirements:
      run:
        - pip
    script:
      - pip check

about:
  license: BSD-3-Clause
  license_file: LICENSE
  summary: Composable style cycles
  homepage: http://github.com/matplotlib/cycler

extra:
  recipe-maintainers:
    - pelson
    - tacaswell
    - jankatins
    - ocefpaf
