name: Building and Rebuilding

on:
  push:
    branches:
      - main

  pull_request:
  workflow_dispatch:

env:
  RATTLER_BUILD_ENABLE_GITHUB_INTEGRATION: true
  # For windows builds
  PYTHONUTF8: 1

jobs:
  setup-rattler-build:
    continue-on-error: false
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: prefix-dev/setup-pixi@v0.5.1
        with:
          pixi-version: "latest"

      - name: Run YAML to Github Output Action
        id: read-yaml
        uses: nichmor/minimal-read-yaml@v0.0.2
        with:
          config: ${{ github.workspace }}/config.yaml

      - name: Restore rattler-build cache
        id: cache-rattler-build-restore
        uses: actions/cache/restore@v4
        with:
          path: |
            .rb-clone/target/release/rattler-build
            .rb-clone/target/release/rattler-build.exe
          key: v4-${{ runner.os }}-rattler-build-${{ steps.read-yaml.outputs['rattler-build.rev'] }}


      - name: Build rattler-build
        if: steps.cache-rattler-build-restore.outputs.cache-hit != 'true'
        run: |
          pixi run repror setup-rattler-build


      - name: Save unix rattler-build
        uses: actions/cache/save@v4
        if: steps.cache-rattler-build-restore.outputs.cache-hit != 'true'
        with:
          path: |
            .rb-clone/target/release/rattler-build
            .rb-clone/target/release/rattler-build.exe
          key: v4-${{ runner.os }}-rattler-build-${{ steps.read-yaml.outputs['rattler-build.rev'] }}

  generate-recipes:
    runs-on: ubuntu-latest
    needs: setup-rattler-build
    outputs:
      recipe: ${{ steps.generate-matrix.outputs.recipes }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: prefix-dev/setup-pixi@v0.5.1
        with:
          pixi-version: "latest"

      - name: Generate matrix
        id: generate-matrix
        run: |
          message=$(pixi r generate-recipes)
          echo $message
          echo "recipes=$message" >> $GITHUB_OUTPUT

  build-and-rebuild-recipes:
    needs: generate-recipes
    name: ${{ matrix.recipe_name }}-${{ matrix.os }}
    continue-on-error: true
    strategy:
      matrix:
        recipe_name: ${{ fromJson(needs.generate-recipes.outputs.recipe) }}
        # os: [ubuntu-latest]
        os: [ubuntu-latest, windows-latest, macos-latest]


    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: prefix-dev/setup-pixi@v0.5.1
        with:
          pixi-version: "latest"

      - name: Run YAML to Github Output Action
        id: read-yaml
        uses: nichmor/minimal-read-yaml@v0.0.2
        with:
          config: ${{ github.workspace }}/config.yaml

      - name: Restore rattler-build cache
        id: cache-rattler-build-restore
        uses: actions/cache/restore@v4
        with:
          path: |
            .rb-clone/target/release/rattler-build
            .rb-clone/target/release/rattler-build.exe
          key: v4-${{ runner.os }}-rattler-build-${{ steps.read-yaml.outputs['rattler-build.rev'] }}
          fail-on-cache-miss: true

      - name: Set timezone to UTC
        if: matrix.os == 'ubuntu-latest'
        run: sudo timedatectl set-timezone UTC

      - name: Set timezone to GMT
        if: matrix.os == 'macos-latest'
        run: sudo systemsetup -settimezone GMT

      - name: Set LANG
        if: matrix.os == 'ubuntu-latest' || matrix.os == 'macos-latest'
        run: echo "LANG=en_US.UTF-8" >> $GITHUB_ENV

      - name: Build recipes and track if hash is equal
        if: matrix.os != 'windows-latest'
        run: |
          pixi run repror build-recipe ${{ matrix.recipe_name }} --rattler-build-exe .rb-clone/target/release/rattler-build

      - name: Build recipes and track if hash is equal
        if: matrix.os == 'windows-latest'
        run: |
          pixi run repror build-recipe ${{ matrix.recipe_name }} --rattler-build-exe .rb-clone\target\release\rattler-build.exe

      - name: Set timezone to Los Angeles
        if: matrix.os == 'ubuntu-latest'
        run: sudo timedatectl set-timezone America/Los_Angeles

      - name: Set timezone to Los Angeles
        if: matrix.os == 'macos-latest'
        run: sudo systemsetup -settimezone America/Los_Angeles

      - name: Set LANG
        if: matrix.os == 'ubuntu-latest' || matrix.os == 'macos-latest'
        run: echo "LANG=et_EE.UTF-8" >> $GITHUB_ENV

      - name: Rebuild recipes and track if hash is equal
        if: matrix.os != 'windows-latest'
        run: |
          pixi run rebuild-recipe ${{ matrix.recipe_name }} --rattler-build-exe .rb-clone/target/release/rattler-build

      - name: Rebuild recipes and track if hash is equal
        if: matrix.os == 'windows-latest'
        run: |
          pixi run rebuild-recipe ${{ matrix.recipe_name }} --rattler-build-exe .rb-clone\target\release\rattler-build.exe

      - name: Upload results
        uses: actions/upload-artifact@v3
        with:
          name: build-info
          path: |
            build_info/
            ci_artifacts/

  statistics:
    runs-on: ubuntu-latest
    needs: build-and-rebuild-recipes

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: prefix-dev/setup-pixi@v0.5.1
        with:
          pixi-version: "latest"

      - uses: actions/download-artifact@v3
        with:
          name: build-info
          path: .

      - run: |
          ls -la build_info/

      - name: Calculate statistics and plot output
        run: |
          REPROR_UPDATE_TOKEN=${{ secrets.GITHUB_TOKEN }} pixi run rewrite-readme --update-remote --remote-branch ${{ github.ref_name }}
