name: Track how repro we are

on:
  push:
    branches:
      - main

  pull_request:
  workflow_dispatch:

env:
  RATTLER_BUILD_ENABLE_GITHUB_INTEGRATION: true

jobs:
  build-recipes-ubunutu-22-04:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - uses: prefix-dev/setup-pixi@v0.5.1
        with:
          pixi-version: "latest"

      - name: Set timezone to UTC
        run: sudo timedatectl set-timezone UTC

      - name: Set LANG
        run: echo "LANG=en_US.UTF-8" >> $GITHUB_ENV

      - name: Verify LANG for Initial Build
        run: echo $LANG

      - name: Build recipes and track if hash is equal
        run: |
          pixi run python src/repror/build_recipe.py ubuntu 22.04

      - name: Upload results
        uses: actions/upload-artifact@v3
        with:
          name: artifacts
          path: |
            build_info/
            artifacts/

  build-recipes-macos-13:
    runs-on: macos-13

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - uses: prefix-dev/setup-pixi@v0.5.1
        with:
          pixi-version: "latest"

      - name: Set timezone to UTC
        run: sudo systemsetup -settimezone GMT

      - name: Set LANG
        run: echo "LANG=en_US.UTF-8" >> $GITHUB_ENV

      - name: Verify LANG for Initial Build
        run: echo $LANG

      - name: Build recipes and track if hash is equal
        run: |
          pixi run python src/repror/build_recipe.py macos 13

      - name: Upload results
        uses: actions/upload-artifact@v3
        with:
          name: artifacts
          path: |
            build_info/
            artifacts/

  build-recipes-windows-2022:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - uses: prefix-dev/setup-pixi@v0.5.1
        with:
          pixi-version: "latest"

      - name: Build recipes and track if hash is equal
        run: |
          pixi run python src/repror/build_recipe.py windows 2022

      - name: Upload results
        uses: actions/upload-artifact@v3
        with:
          name: artifacts
          path: |
            build_info/
            artifacts/

  rebuild-recipes-ubuntu-22-04:
    runs-on: ubuntu-22.04
    needs: build-recipes-ubunutu-22-04

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - uses: prefix-dev/setup-pixi@v0.5.1
        with:
          pixi-version: "latest"

      - uses: actions/download-artifact@v3
        with:
          name: artifacts
          path: .

      - name: Set timezone to PST
        run: sudo timedatectl set-timezone America/Los_Angeles

      - name: Set LANG
        run: echo "LANG=et_EE.UTF-8" >> $GITHUB_ENV

      - name: Verify LANG for Initial Build
        run: echo $LANG

      - name: Rebuild recipes and track if hash is equal
        run: |
          # sudo apt-get install libssl-dev
          pixi run python src/repror/rebuild_recipe.py ubuntu 22.04 20.04

      - name: Upload diffoscope
        uses: actions/upload-artifact@v3
        with:
          name: build-info
          path: |
            build_info/ubuntu
            diffoscope_output/
            ci_artifacts/

  rebuild-recipes-macos-13:
    runs-on: macos-13
    needs: build-recipes-macos-13

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - uses: prefix-dev/setup-pixi@v0.5.1
        with:
          pixi-version: "latest"

      - uses: actions/download-artifact@v3
        with:
          name: artifacts
          path: .

      - name: Set timezone to PST
        run: sudo systemsetup -settimezone America/Los_Angeles

      - name: Set LANG
        run: echo "LANG=et_EE.UTF-8" >> $GITHUB_ENV

      - name: Verify LANG for Initial Build
        run: echo $LANG

      - name: Rebuild recipes and track if hash is equal
        run: |
          pixi run python src/repror/rebuild_recipe.py macos 13 12

      - name: Upload build info
        uses: actions/upload-artifact@v3
        with:
          name: build-info
          path: |
            build_info/macos
            diffoscope_output/
            ci_artifacts/

  rebuild-recipes-windows-2022:
    runs-on: windows-2022
    needs: build-recipes-windows-2022

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - uses: prefix-dev/setup-pixi@v0.5.1
        with:
          pixi-version: "latest"

      - uses: actions/download-artifact@v3
        with:
          name: artifacts
          path: .

      - name: Rebuild recipes and track if hash is equal
        run: |
          # sudo apt-get install libssl-dev
          pixi run python src/repror/rebuild_recipe.py windows 2022 2019

      - name: Upload diffoscope
        uses: actions/upload-artifact@v3
        with:
          name: build-info
          path: |
            build_info/ubuntu
            ci_artifacts/

  statistics:
    runs-on: ubuntu-latest
    needs: [rebuild-recipes-ubuntu-20-04, rebuild-recipes-macos-12]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - uses: prefix-dev/setup-pixi@v0.5.1
        with:
          pixi-version: "latest"

      - uses: actions/download-artifact@v3
        with:
          name: build-info
          path: .

      - run: |
          ls -la build_info/
          ls -la build_info/ubuntu

      - name: Calculate statistics and plot output
        run: |
          pixi run python src/repror/statistics.py ubuntu_22.04_20.04 macos_13_12

      - name: Commit and push changes
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add data/history.json
          git add data/chart.png
          git add README.md
          git commit -m "Update file via GitHub Action"
          git push
